### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by Bubus555** [ksahlin/BESST#18]
Hi,

I use BESST tool with the version 1.2.3.
When I want to scaffold my contig file with only Mate Pair librarie, it works very well. 
However; when I want to scaffold with PE librarie and MP librairie, I get the following error:

-----------------------------------------------------------------------------------------------------------------------
/env/ig/soft/ig/besst-1.2.3/el6-x86_64-generic/lib/python2.7/site-packages/BESST/CreateGraph.py:339: RuntimeWarning: divide by zero encountered in double_scalars
  std_dev_score = min(std_dev / std_dev_d_eq_0, std_dev_d_eq_0 / std_dev) #+ span_score #+ min(n/E_links, E_links/float(n))
Traceback (most recent call last):
  File "/env/ig/soft/ig/besst-1.2.3/el6-x86_64-generic/bin/runBESST", line 346, in <module>
    main(args)
  File "/env/ig/soft/ig/besst-1.2.3/el6-x86_64-generic/bin/runBESST", line 148, in main
    MS.Algorithm(G, G_prime, Contigs, small_contigs, Scaffolds, small_scaffolds, Information, param)   # Make scaffolds, store the complex areas (consisting of contig/scaffold) in F, store the created scaffold
s in Scaffolds, update Contigs
  File "/env/ig/soft/ig/besst-1.2.3/el6-x86_64-generic/lib/python2.7/site-packages/BESST/MakeScaffolds.py", line 84, in Algorithm
    G, Contigs, Scaffolds = RemoveLoops(G, G_prime, Scaffolds, Contigs, Information, param)    #step4
  File "/env/ig/soft/ig/besst-1.2.3/el6-x86_64-generic/lib/python2.7/site-packages/BESST/MakeScaffolds.py", line 248, in RemoveLoops
    for graph in graphs:
  File "/env/ig/soft/ig/python-2.7.5/el6-x86_64-generic/lib/python2.7/site-packages/networkx/algorithms/components/connected.py", line 92, in connected_component_subgraphs
    for c in connected_components(G):
  File "/env/ig/soft/ig/python-2.7.5/el6-x86_64-generic/lib/python2.7/site-packages/networkx/algorithms/components/connected.py", line 54, in connected_components
    for v in G:
RuntimeError: dictionary changed size during iteration
-----------------------------------------------------------------------------------------------------------------------

It seems to be the same error reported on the link bellow:
https://github.com/ksahlin/BESST_RNA/issues/2

Do you have any idea about this error ?

**Comment by ksahlin** [comment]
Hi,

Thanks for your report!
This bug is fixed in later versions of BESST, and more precisely in this commit: https://github.com/ksahlin/BESST/commit/bdbd3142cafa752f927ab5eacb95f309e9a28b23

To fix this issue install the current version of BESST.

Best,
Kristoffer

**Comment by Bubus555** [comment]
Thanks you a lot, I just tried the last version of BESST and it works!

Best,

Léo

**Comment by ksahlin** [comment]
Great!

If you have any questions regarding results or running instructions, mail me at ksahlin@kth.se

Best,
Kristoffer
