### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by dbrowneup** [ksahlin/BESST#49]
Hi Kristoffer,

Was running BESST today when I unexpectedly hit a new bug. On pass4 of scaffolding, BESST got choked up on something:

```Python
enter Between scaf node:5800, scaffold progression 99.8%. 
Total nr of paths found: 5911 with score larger than: 1.5
Hit path_threshold of 100000 iterations! consider increase --iter <int> parameter to over 100000 if speed of BESST is not a problem. Standard increase is, e.g., 2-10x of curr
ent value
Elapsed time single core pathfinder:  39437.362112
Writing out scaffolding results for step 3  ...
Choosing mode: 13590
mu_adjusted:14844.0182109, sigma_adjusted:3295.68336926, skewness_adjusted:0.598540321428
mode adj: 13590
median adj 14372
Creating contig graph with library:  HISAT2_L20K/HISAT2_L20K.bam
Traceback (most recent call last):
  File "/scratch/user/dbrowne/Software/BESST/runBESST", line 415, in <module>
    main(args)
  File "/scratch/user/dbrowne/Software/BESST/runBESST", line 177, in main
    (G, G_prime) = CG.PE(Contigs, Scaffolds, Information, C_dict, param, small_contigs, small_scaffolds, bam_file)      #Create graph, single out too short contigs/scaffolds 
and store them in F
  File "/scratch/user/dbrowne/Software/BESST/BESST/CreateGraph.py", line 300, in PE
    GiveScoreOnEdges(G, Scaffolds, small_scaffolds, Contigs, param, Information, plot)
  File "/scratch/user/dbrowne/Software/BESST/BESST/CreateGraph.py", line 538, in GiveScoreOnEdges
    std_dev_d_eq_0 = conditional_stddevs[int(gap)]
IndexError: list index out of range
```

I'm kind of at a loss for how to debug this. I've scaffolded with this library before and haven't had this problem. Any thoughts on where I should look first to troubleshoot?

Best,
Dan

**Comment by dbrowneup** [comment]
Duplicate of https://github.com/ksahlin/BESST/issues/41
