### ISSUE TITLE
Incompatibility with networkx 2.0

### ISSUE THREAD

**Issue by mascherIPK** [ksahlin/BESST#68]
BESST does not work networks 2.0.

https://networkx.github.io/documentation/stable/release/release_2.0.html

The BESST error message was:

Traceback (most recent call last):
 File "/opt/Bio/BESST/2.2.7/bin/runBESST", line 424, in <module>
   main(args)
 File "/opt/Bio/BESST/2.2.7/bin/runBESST", line 177, in main
   (G, G_prime) = CG.PE(Contigs, Scaffolds, Information, C_dict, param, small_contigs, small_scaffolds, bam_file)      #Create graph, single out too short contigs/scaffolds and store them in F
 File "/opt/Bio/BESST/2.2.7/venv/lib/python2.7/site-packages/BESST/CreateGraph.py", line 202, in PE
   CreateEdge(cont_obj1, cont_obj2, scaf_obj1, scaf_obj2, G_prime, param, alignedread, counter, contig1, contig2, save_obs=False)
 File "/opt/Bio/BESST/2.2.7/venv/lib/python2.7/site-packages/BESST/CreateGraph.py", line 841, in CreateEdge
   G.edge[(scaf_obj1.name, scaf_side1)][(scaf_obj2.name, scaf_side2)]['obs_sq'] = (obs1 + obs2) ** 2
AttributeError: 'Graph' object has no attribute 'edge'

Downgrading to 1.10 solved the issue.

A version constraint should be added.

**Comment by ksahlin** [comment]
Thanks for reporting!

Fixed in 342c36771637d303ae002a64fbf73b71eb9442d3
