### ISSUE TITLE
TypeError: PosDirCalculatorPE() missing 5 required positional arguments: 'cont2pos', 'matepos', 's2len', 'cont2_len', and 'read_len'

### ISSUE THREAD

**Issue by JuniusH** [ksahlin/BESST#85]
Hello there, good day.
I am trying to run BESST with test data. I install it via conda, then I uninstall the networkx from the package and install the networkx==1.11 version, since some issues discussed about this.

I run it with testdata1 and it finished with result folder contained:
Statistics.txt  
haplotypes.fa  
pass1.

Then, when i run it with testdata2, it got error with message:
`Traceback (most recent call last):
  File "/opt/conda/envs/besst-env/bin/runBESST", line 421, in <module>
    main(args)
  File "/opt/conda/envs/besst-env/bin/runBESST", line 182, in main
    (G, G_prime) = CG.PE(Contigs, Scaffolds, Information, C_dict, param, small_contigs, small_scaffolds, bam_file)      #Create graph, single out too short contigs/scaffolds and store them in F
  File "/opt/conda/envs/besst-env/lib/python3.7/site-packages/BESST/CreateGraph.py", line 198, in PE
    CreateEdge(cont_obj1, cont_obj2, scaf_obj1, scaf_obj2, G_prime, param, alignedread, counter, contig1, contig2, save_obs=False)
  File "/opt/conda/envs/besst-env/lib/python3.7/site-packages/BESST/CreateGraph.py", line 831, in CreateEdge
    (obs1, obs2, scaf_side1, scaf_side2) = PosDirCalculatorPE(cont_dir1, read_dir, cont1_pos, readpos, s1len, cont1_len, cont_dir2, mate_dir)
TypeError: PosDirCalculatorPE() missing 5 required positional arguments: 'cont2pos', 'matepos', 's2len', 'cont2_len', and 'read_len'`

What could be the problem? And how can I solve it? Thank you

**Comment by ksahlin** [comment]
Looks weird, not sure. Hope you've either solved it, it worked on other dataset(s) you wanted to run on, or found other solutions.
